#!/usr/bin/env python3

# reference: https://pandas.pydata.org/docs/reference/index.html
import pandas as pd
import datetime

config = {
    "last_n_days": 30,
    "output_file": "./built/dev1.html",
}


def dates():
    today = pd.Timestamp.today().date()
    # TODO should input be a range or a date?
    oldest = today - pd.Timedelta(config['last_n_days'], 'd')
    return pd.date_range(start=oldest, end=today, normalize=True)


def prettify(df):
    html_table = df.to_html()
    title = "Report of Loop Habit Tracker"
    style = '''
      body {
        font-family: sans-serif;
      }
      table {
        border-collapse: collapse;
      }
      thead {
        top: 0;
        background-color: dark-cyan
      }
      td, th {
        text-align: center;
      }
    '''
    html = f'''
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{title}</title>
  <style>{style}</style>
</head>
<body>
  <h1>{title}</h1>
  <main>{html_table}</main>
</body>
</html>
    '''

    return html


def main():
    df = pd.read_csv(
        './example-data.d/Checkmarks.csv',
        index_col=0
    )

    df.index = pd.to_datetime(df.index).strftime('%d.%b.')

    df = df.replace(to_replace={
        -1: "❌",
        0: "?",
        2: "✅",
        1: "🆗",
    })

    try:
        df = df.loc[dates()]
    except KeyError:
        print("Not all past days exist in the exported file. Continuing anyway.")

    html = prettify(df.T)

    # XXX work in progress
    with open(config["output_file"], 'w') as file:
        file.write(html)


main()
