#!/usr/bin/env python3

# reference: https://pandas.pydata.org/docs/reference/index.html
import pandas as pd
import datetime

config = {
    "last_n_days": 30,
}


def dates():
    today = pd.Timestamp.today().date()
    # TODO should input be a range or a date?
    oldest = today - pd.Timedelta(config['last_n_days'], 'd')
    return pd.date_range(start=oldest, end=today, normalize=True)


def main():
    df = pd.read_csv(
        './example-data.d/Checkmarks.csv',
        index_col=0
    )

    df.index = pd.to_datetime(df.index)

    df = df.replace(to_replace={
        -1: "❌",
        2: "✅",
        1: "☐",
    })

    # XXX work in progress
    df = df.loc[dates()]
    # df = df.head(config["last_n_days"])
    df.to_csv('built/dev.csv')


main()
